# Shared setup initialization

WORKSTATION_SETUP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DEFAULT_RUBY_VERSION=2.7.3
DEFAULT_PYTHON_VERSION=3.8.5
DEFAULT_NODEJS_VERSION=10.15.2
DEFAULT_TF_VERSION=0.14.7
DEFAULT_TG_VERSION=0.28.3
